<a href="https://colab.research.google.com/github/sidhu2690/ai-from-scratch/blob/main/00_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

image = np.array([
    [1,2,3,4,5],
    [4,5,6,7,8],
    [7,8,9,1,2],
    [1,3,5,7,9],
    [2,4,6,8,0]
], dtype=float)


In [19]:
filter = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
], dtype=float)


In [20]:
def iterate_regions(image, filter_size=3):
    h, w = image.shape
    f = filter_size

    for i in range(h - f + 1):
        for j in range(w - f + 1):
            region = image[i:i+f, j:j+f]
            yield i, j, region


In [21]:
for i, j, region in iterate_regions(image):
    print("Position:", i, j)
    print(region)
    print()


Position: 0 0
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Position: 0 1
[[2. 3. 4.]
 [5. 6. 7.]
 [8. 9. 1.]]

Position: 0 2
[[3. 4. 5.]
 [6. 7. 8.]
 [9. 1. 2.]]

Position: 1 0
[[4. 5. 6.]
 [7. 8. 9.]
 [1. 3. 5.]]

Position: 1 1
[[5. 6. 7.]
 [8. 9. 1.]
 [3. 5. 7.]]

Position: 1 2
[[6. 7. 8.]
 [9. 1. 2.]
 [5. 7. 9.]]

Position: 2 0
[[7. 8. 9.]
 [1. 3. 5.]
 [2. 4. 6.]]

Position: 2 1
[[8. 9. 1.]
 [3. 5. 7.]
 [4. 6. 8.]]

Position: 2 2
[[9. 1. 2.]
 [5. 7. 9.]
 [6. 8. 0.]]



In [23]:
output = np.zeros((3, 3))

for i, j, region in iterate_regions(image):
    output[i, j] = np.sum(region * filter)

output

array([[ -6.,   3.,   3.],
       [ -8.,   1.,   1.],
       [-10.,  -1.,   9.]])

# Multi-Channel Case

In [34]:
image = np.random.randint(0, 10, (5,5,3))
filter = np.random.randint(-2, 3, (3,3,3))

def iterate_regions(image, f=3):
    H, W, C = image.shape
    for i in range(H - f + 1):
        for j in range(W - f + 1):
            yield i, j, image[i:i+f, j:j+f, :]

for i, j, region in iterate_regions(image):
    print("pos:", i, j)
    print(region)
    print()


pos: 0 0
[[[8 4 1]
  [8 0 2]
  [7 6 6]]

 [[3 6 9]
  [1 5 1]
  [2 1 9]]

 [[1 3 4]
  [3 7 3]
  [1 7 1]]]

pos: 0 1
[[[8 0 2]
  [7 6 6]
  [1 1 5]]

 [[1 5 1]
  [2 1 9]
  [8 5 4]]

 [[3 7 3]
  [1 7 1]
  [6 6 7]]]

pos: 0 2
[[[7 6 6]
  [1 1 5]
  [0 4 2]]

 [[2 1 9]
  [8 5 4]
  [3 7 0]]

 [[1 7 1]
  [6 6 7]
  [8 6 1]]]

pos: 1 0
[[[3 6 9]
  [1 5 1]
  [2 1 9]]

 [[1 3 4]
  [3 7 3]
  [1 7 1]]

 [[4 7 5]
  [3 3 4]
  [2 5 4]]]

pos: 1 1
[[[1 5 1]
  [2 1 9]
  [8 5 4]]

 [[3 7 3]
  [1 7 1]
  [6 6 7]]

 [[3 3 4]
  [2 5 4]
  [5 1 9]]]

pos: 1 2
[[[2 1 9]
  [8 5 4]
  [3 7 0]]

 [[1 7 1]
  [6 6 7]
  [8 6 1]]

 [[2 5 4]
  [5 1 9]
  [8 4 9]]]

pos: 2 0
[[[1 3 4]
  [3 7 3]
  [1 7 1]]

 [[4 7 5]
  [3 3 4]
  [2 5 4]]

 [[3 9 2]
  [9 2 6]
  [6 5 9]]]

pos: 2 1
[[[3 7 3]
  [1 7 1]
  [6 6 7]]

 [[3 3 4]
  [2 5 4]
  [5 1 9]]

 [[9 2 6]
  [6 5 9]
  [6 7 3]]]

pos: 2 2
[[[1 7 1]
  [6 6 7]
  [8 6 1]]

 [[2 5 4]
  [5 1 9]
  [8 4 9]]

 [[6 5 9]
  [6 7 3]
  [8 3 8]]]



In [37]:
output = np.zeros((3,3))

for i, j, region in iterate_regions(image):
    output[i, j] = np.sum(region * filter)

output

array([[ 24.,  -3., -12.],
       [-26., -12., -29.],
       [-43.,  10.,   4.]])