<a href="https://colab.research.google.com/github/sidhu2690/ai-from-scratch/blob/main/01_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import torch

#### In this notebook, we will be discussing tensor manipulation and automatic differentiation.

#### Basic Operations

In [28]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])

In [29]:
a + 10

tensor([11, 12, 13, 14])

In [30]:
a * 10

tensor([10, 20, 30, 40])

In [31]:
a - 10

tensor([-9, -8, -7, -6])

#### Built-in functions

In [33]:
torch.multiply(a, 10)

tensor([10, 20, 30, 40])

In [34]:
torch.add(a, a)

tensor([2, 4, 6, 8])

In [36]:
torch.mul(a, a)  # dot product

tensor([ 1,  4,  9, 16])

In [37]:
torch.sub(a, 1)

tensor([0, 1, 2, 3])

### Dot Product / Matrix Multiplication

#### 1. `torch.matmul`
```python
# Performs matrix multiplication or dot product
# Works for vectors and matrices
result = torch.matmul(a, b)
```

#### 2. `@` operator
```python
# Python shorthand for matrix multiplication
result = a @ b
```

#### 3. `torch.dot` (for 1-D vectors only)
```python
# Computes dot product of two 1-D tensors (vectors)
result = torch.dot(a, b)
```

#### 4. `torch.mm` (for 2-D matrices only)
```python
# Performs matrix multiplication of two 2-D tensors
result = torch.mm(a, b)
```


# Seed

### Setting Random Seed

#### `torch.manual_seed()`
```python
# Sets the seed for generating random numbers
# Ensures reproducible results
torch.manual_seed(seed_value)
```

#### Example
```python
torch.manual_seed(42)  # any integer
x = torch.rand(3)
print(x)
```

> Running this code multiple times will give the **same random numbers**.


In [55]:
torch.manual_seed(42)
x = torch.rand(3)
print(x)

tensor([0.8823, 0.9150, 0.3829])


In [53]:
torch.manual_seed(42)
x = torch.rand(3)
print(x)

tensor([0.8823, 0.9150, 0.3829])


# Some built-in function

In [56]:
a = torch.arange(1, 20, 2)

In [57]:
a.type()

'torch.LongTensor'

In [58]:
a.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

Here, we need to convert the values to floating-point numbers to calculate the mean

In [62]:
a.to(dtype = torch.float32).mean()

tensor(10.)

In [63]:
torch.max(a)

tensor(19)

In [64]:
torch.sum(a)

tensor(100)

In [66]:
torch.argmax(a)  # Find the pos of max value

tensor(9)

In [67]:
torch.argmin(a)

tensor(0)

In [72]:
print(a, a.shape)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]) torch.Size([10])


In [73]:
a.reshape(5, 2)

tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]])

In [74]:
a.reshape(-1, 1)

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])

In [77]:
torch.stack([a, a], axis = 0)

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [78]:
torch.stack([a, a], axis = 1)

tensor([[ 1,  1],
        [ 3,  3],
        [ 5,  5],
        [ 7,  7],
        [ 9,  9],
        [11, 11],
        [13, 13],
        [15, 15],
        [17, 17],
        [19, 19]])

In [110]:
b = torch.randn(1, 2, 2)

In [111]:
b = b.squeeze()
b.shape

torch.Size([2, 2])

In [112]:
b = b.unsqueeze(dim = 2)
b.shape

torch.Size([2, 2, 1])

In [113]:
b = b.permute(2, 0, 1)
b.shape

torch.Size([1, 2, 2])

In [114]:
b_temp = torch.cat([b, b], axis = 0)
b_temp, b_temp.shape

(tensor([[[-0.7150,  0.1280],
          [-0.1603, -2.2161]],
 
         [[-0.7150,  0.1280],
          [-0.1603, -2.2161]]]),
 torch.Size([2, 2, 2]))

In [115]:
b_temp = torch.cat([b, b], axis = 1)
b_temp, b_temp.shape

(tensor([[[-0.7150,  0.1280],
          [-0.1603, -2.2161],
          [-0.7150,  0.1280],
          [-0.1603, -2.2161]]]),
 torch.Size([1, 4, 2]))

# CUDA

In [116]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [117]:
device

'cuda'

In [118]:
torch.cuda.device_count()

1

# Automatic Differentiation Example


In [119]:
# Create a tensor and track gradients
x = torch.tensor(2.0, requires_grad=True)

# Define a function f(x) = 3*x^2 + 2*x + 1
fx = 3*x**2 + 2*x + 1

# Compute gradient
fx.backward()

# Print gradient (df/dx at x=2)
print(x.grad.item())  # 14.0, since df/dx = 6*x + 2 = 6*2 + 2


14.0
