<a href="https://colab.research.google.com/github/sidhu2690/ai-from-scratch/blob/main/00_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.8.0+cu126'

# Tensors in Torch

#### Scalars in torch

These are the zero-dimensional tensors, or scalars

In [4]:
scalar = torch.tensor(7)

In [6]:
scalar.ndim  # To check dimension of a tensor

0

In [7]:
scalar.shape # or scalar.size()

torch.Size([])

#### 1 Dimensional Tensor

In [10]:
one_dim_tensor = torch.tensor([1, 2, 3])

In [11]:
one_dim_tensor.ndim

1

In [12]:
one_dim_tensor.shape

torch.Size([3])

#### 2 Dimensional Tensor

In [13]:
two_dim_tensor = torch.tensor([[1, 2, 3],
                               [4, 5, 6]])

In [14]:
two_dim_tensor.ndim

2

In [15]:
two_dim_tensor.shape

torch.Size([2, 3])

Similarly, we can create tensors of multiple dimensions.

# Random Tensor

In [17]:
random_tensor = torch.rand(size = (2, 3))
random_tensor

tensor([[0.9856, 0.6542, 0.9101],
        [0.0472, 0.8713, 0.1296]])

In [19]:
random_tensor.dtype

torch.float32

#### `torch.rand`
```python
# Creates a tensor with random values sampled from a uniform distribution over [0, 1)
torch.rand(size)
```

#### `torch.randn`
```python
# Creates a tensor with random values sampled from a standard normal distribution (mean=0, std=1)
torch.randn(size)
```

#### `torch.Tensor.uniform_()`
```python
# Fills a tensor with values sampled from a uniform distribution over [a, b)
tensor.uniform_(a, b)
```

#### `torch.randint`
```python
# Creates a tensor with random integers in the range [low, high)
torch.randint(low, high, size)
```


# Zeros and Ones

In [20]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
a = torch.randint(1, 10, (2, 2))
a

tensor([[1, 1],
        [8, 8]])

In [24]:
torch.ones_like(a)

tensor([[1, 1],
        [1, 1]])

In [25]:
torch.zeros_like(a)

tensor([[0, 0],
        [0, 0]])

#### `torch.ones`
```python
# Creates a tensor filled with 1s
torch.ones(size)
```

#### `torch.zeros`
```python
# Creates a tensor filled with 0s
torch.zeros(size)
```

#### `torch.ones_like()`
```python
# Creates a tensor of 1s with the same shape as another tensor
torch.ones_like(tensor)
```

#### `torch.zeros_like()`
```python
# Creates a tensor of 0s with the same shape as another tensor
torch.zeros_like(tensor)
```


### Range

In [26]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

#### `torch.arange`
```python
# Creates a 1-D tensor with values from start (inclusive) to end (exclusive) with a given step
torch.arange(start, end, step=1)
```


# Data Types

## Integer dtypes
#### `torch.int8`
```python
# 8-bit signed integer
torch.int8
```

#### `torch.int16` / `torch.short`
```python
# 16-bit signed integer
torch.int16
torch.short
```

#### `torch.int32` / `torch.int`
```python
# 32-bit signed integer
torch.int32
torch.int
```

#### `torch.int64` / `torch.long`
```python
# 64-bit signed integer
torch.int64
torch.long
```

---

## Floating point dtypes
#### `torch.float16` / `torch.half`
```python
# 16-bit floating point
torch.float16
torch.half
```

#### `torch.float32` / `torch.float`
```python
# 32-bit floating point
torch.float32
torch.float
```

#### `torch.float64` / `torch.double`
```python
# 64-bit floating point
torch.float64
torch.double
```

---

## Complex dtypes
#### `torch.complex64`
```python
# 64-bit complex number (32-bit real + 32-bit imaginary)
torch.complex64
```

#### `torch.complex128`
```python
# 128-bit complex number (64-bit real + 64-bit imaginary)
torch.complex128
```

---

## Boolean dtype
#### `torch.bool`
```python
# Boolean tensor (True or False)
torch.bool
```
